name: Dist plugin

on:
    push:
      tags:
        - 'v*'
    workflow_dispatch:
        inputs:
            tag:
                description: 'Semver tag (e.g., v1.2.3) - optional when run manually'
                required: false
                type: string

concurrency:
    group: ${{ github.workflow }}-${{ github.ref || inputs.tag || github.run_id }}
    cancel-in-progress: true

permissions:
    contents: write

jobs:
    build:
        name: Build assets
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node-version: [20.x]
                os: [ubuntu-latest]
                php: [8.2]
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - uses: pnpm/action-setup@v4
              with:
                  version: 10

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Build assets
              run: pnpm run build

            - name: Create artifacts
              shell: bash
              run: pnpm run plugin-zip

            - name: Resolve tag
              id: tag
              run: |
                  if [ -n "${{ github.ref_name }}" ]; then
                      echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
                  elif [ -n "${{ inputs.tag }}" ]; then
                      echo "tag=${{ inputs.tag }}" >> $GITHUB_OUTPUT
                  else
                      echo "No tag provided or detected"; exit 1
                  fi

            - name: Check version consistency
              run: |
                  TAG="${{ steps.tag.outputs.tag }}"
                  TAG="${TAG#v}"
                  grep -E "Version:\s*${TAG}" content-aggregator.php
                  grep -E "^Stable tag:\s*${TAG}" readme.txt

            - name: Extract changelog section for this tag
              id: changelog
              run: |
                  TAG="${{ steps.tag.outputs.tag }}"
                  TAG="${TAG#v}"
                  notes=$(awk -v ver="$TAG" '
                      BEGIN{ in_ch=0; in_ver=0 }
                      /^==[[:space:]]*Changelog[[:space:]]*==/ { in_ch=1; next }
                      in_ch && $0 ~ "^=[[:space:]]*"ver"([[:space:]].*)?=" { in_ver=1; next }
                      in_ch && in_ver && $0 ~ "^=[[:space:]]*[0-9]+\\.[0-9]+(\\.[0-9]+)?([-.][A-Za-z0-9.]+)?([[:space:]].*)?=" { exit }
                      in_ch && in_ver { print }
                  ' readme.txt)

                  if [ -z "$notes" ]; then
                      echo "No changelog section found for $TAG, fallback to default notes."
                      notes="Release $TAG"
                  fi

                  {
                      echo "notes<<__EOF__"
                      echo "$notes"
                      echo "__EOF__"
                  } >> "$GITHUB_OUTPUT"

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ steps.tag.outputs.tag }}
                  name: ${{ steps.tag.outputs.tag }}
                  body: ${{ steps.changelog.outputs.notes }}
                  draft: false
                  prerelease: ${{ contains(steps.tag.outputs.tag, '-rc') || contains(steps.tag.outputs.tag, '-beta') }}
                  files: content-aggregator.zip

            - name: Unzip package for WP.org deploy
              run: |
                  rm -rf dist
                  mkdir -p dist
                  unzip -q content-aggregator.zip -d dist
                  if [ ! -d "dist/content-aggregator" ]; then
                      mkdir -p dist/content-aggregator
                      shopt -s dotglob
                      mv dist/* dist/content-aggregator/ || true
                  fi

            - name: Downgrade PHP 8.1+ keywords # TODO: temp fix to remove when WP.org upgrade php check to 8.2
              run: find dist -type f -name "*.php" -exec sed -i -r 's/\<readonly[[:space:]]+class\>/class/g' {} \;

            - name: Install SVN
              run: sudo apt-get update && sudo apt-get install -y subversion

            - name: Deploy to WordPress.org
              uses: 10up/action-wordpress-plugin-deploy@stable
              env:
                  SLUG: content-aggregator
                  BUILD_DIR: dist/content-aggregator
                  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
