name: Dist plugin

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build assets
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          node-version: [20.x]
          os: [ubuntu-latest]
          php: [8.1]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build assets
        run: pnpm run prod

      - name: Prepare artifacts
        run: pnpm run package:prepare

      - name: Create artifacts
        shell: bash
        run: pnpm run package

      - name: Release
        uses: actions/upload-artifact@v4
        with:
            name: github.ref
            path: content-aggregator.zip
            if-no-files-found: 'error'
            overwrite: true
